Update docker.yml

diff --git a/.github/workflows/docker.yml b/.github/workflows/docker.yml
--- a/.github/workflows/docker.yml
+++ b/.github/workflows/docker.yml
@@ -1,14 +1,30 @@
-name: Docker Image CI
+name: Deploy to Production
+
 on:
   push:
-    branches: [ "main" ]
-  pull_request:
-    branches: [ "main" ]
+    branches:
+      - main
+
 jobs:
-  build:
+  create_separate_branch:
     runs-on: ubuntu-latest
+
     steps:
-      - name: Checkout code
+      - name: Checkout main branch
+        uses: actions/checkout@v2
+        with:
+          ref: main
+
+      - name: Create separate branch
+        run: |
+          git checkout -b main_clone
+          git push origin main_clone
+
+  deploy:
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Deploy changes to production
         uses: actions/checkout@v2
       - name: Build the Docker image
         run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/git:v1
@@ -19,18 +35,18 @@ jobs:
           password: ${{ secrets.DOCKER_PASSWORD }}
       - name: Build and push Docker image
         run: docker push ${{ secrets.DOCKER_USERNAME }}/git:v1
-  scan:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v2
-     # Install Trivy
-      - name: Install Trivy
+        
+      - name: Check deployment status
         run: |
-          wget https://github.com/aquasecurity/trivy/releases/download/v0.17.2/trivy_0.17.2_Linux-64bit.tar.gz
-          tar zxvf trivy_0.17.2_Linux-64bit.tar.gz
-          sudo mv trivy /usr/local/bin/
-          rm trivy_0.17.2_Linux-64bit.tar.gz
-      # Scan the Docker image
-      - name: Scan Docker image with Trivy
-        run: trivy ${{ secrets.DOCKER_USERNAME }}/git:v1
+          if [ $? -ne 0 ]; then
+            echo "Deployment failed. Creating separate branch."
+            git checkout -b main_clone
+            git add .
+            git commit -m "Deployment error. Creating separate branch"
+            git push origin main_clone
+          fi
+
+          # Regardless of the deployment status, merge separate_branch back to main
+          git checkout main
+          git merge main_clone
+          git push origin main
